title: Prefetch - Suspicious DeviceCredentialDeployment.exe Execution
description: Detects suspicious execution of DeviceCredentialDeployment.exe based
  on prefetch data. Device Credential Deployment.
status: experimental
logsource:
  product: velociraptor
  category: execution
  service: prefetch
detection:
  selection:
    Executable: DEVICECREDENTIALDEPLOYMENT.EXE
  condition: selection
level: medium
tags:
- attack.lolbas
- attack.t1564
references:
- https://lolbas-project.github.io/
author: ilo
date: 2025/03/12
