title: Prefetch - Suspicious SettingSyncHost.exe Execution
description: Detects suspicious execution of SettingSyncHost.exe based on prefetch
  data. Host Process for Setting Synchronization.
status: experimental
logsource:
  product: velociraptor
  category: execution
  service: prefetch
detection:
  selection:
    Executable: SETTINGSYNCHOST.EXE
  condition: selection
level: medium
tags:
- attack.lolbas
- attack.t1218
references:
- https://lolbas-project.github.io/
author: ilo
date: 2025/03/12
